dist: xenial
sudo: false
language: ruby
cache: bundler
rvm:
- 2.5.1

install:
  # Install Jekyll and dependencies
  - bundle install
before_script: bundle update
script: bundle exec rake site:deploy --quiet #--trace

env:
  global:
    secure: "IHIhZYs6UxGYVjuuszmhIRv1clQ/SBGj9msJa73ooF2JLl44zlCzVXANJVVgJ8KhpwxhKVwFJqQB0e/3IuvESKQjeFGPkCDkU6+wbwbzu5YGUlf58eLj6iWXRE8UnDNvv86Kz9dh6MrfLNE2ZO/+oCHMFm+cenR7NhZjyLD0+2Th4tPq3nlS+DwvE6m83KrN3z16dKTbWU+P6LK18B0KbkER4AI2KxiQLvRqT2XQEhAh+b4l75LT07e8pa6Tz9j/1cL/4WTdPykcUxQ2ziCL5EGbjPWHIu8ZCoSrtlgQbnbanjMv+aUGTRPrNYDFGOccjE9WP9BHoV2Xgm274/gcvOtpNgfWNxTbnVheJwabythIZIEHMnGgIjC+dxiFdR4TpDklc4+qq4Jel1XJGnPBtUAzZRqd4UbnK8no2iAtuDbqfZBzwIIiQ8wYO1Y+og/RKLSGqEx05QhIbxbImZWMceAHDQLKS1Bo94jwdYPV0HyVUqbnLOFBOyrmPTbRMtDtNomotyIaE2Bcwyq94HCMryWD9vNAY+Gu+kvUXnPcnlqJiCD7KT5ew0CByWO/3IYk/bfAlXaftVVeq+rixd6GnZrvNeoERs8GTAYa6xvNegWuQEVYrh24Z/IPzqcTpqRYV+ihWjS75XApWislyqD8rOahGzxiPeS8p1O75WYV2Ko="
branches:
  only:
    - master
